Added Loan Approval Support
frap129/cs471-project pull request #54
Opened 2021-05-30 16:19 UTC by TytanRock

Closes #49

2021-05-30 17:41 UTC, TytanRock commented
Tested this on ec2 server with SoapUI, verified the following:
 - Approving a loan changes status to APPROVED in database
 - Denying a loan changes status to DENIED in database
 - Approving/Denying a non-PENDING loan returns an error
 - UserID not being a loanofficer returns an error
 - BankOfficer's BankId not matching Loan's BankId returns an error

2021-05-31 00:50 UTC, AndyGabler commented
Other than the need to `userId` to be passed to the frontend somewhere, preferably in login, this looks good to me.

2021-06-01 14:16 UTC, frap129 approved these changes
Looks good to me!

2021-06-01 18:18 UTC, AndyGabler requested changes

2021-06-02 03:40 UTC, AndyGabler approved these changes

2021-06-02 03:40 UTC, merged